FROM golang:1.20

RUN go install github.com/cosmtrek/air@latest

WORKDIR /usr/src/app
# pre-copy/cache go.mod for pre-downloading dependencies and only redownloading them in subsequent builds if they change
COPY go.mod go.sum ./
RUN go mod download && go mod verify

# COPY . .
# RUN go build -o ./build/

EXPOSE 3000

CMD ["air", "-c", ".air.toml.docker"]